server:
  port: 8083


spring:
  application:
    name: USER-SERVICE

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8084/eureka/
  instance:
    hostname: localhost
